// <auto-generated />
using Commander.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Commander.Migrations
{
  [DbContext(typeof(CommanderDbContext))]
  [Migration("20200810215217_Initial")]
  partial class Initial
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
          .HasAnnotation("ProductVersion", "3.1.6")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      modelBuilder.Entity("Commander.Models.Command", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<string>("HowTo")
                      .IsRequired()
                      .HasColumnType("character varying(255)")
                      .HasMaxLength(255);

            b.Property<string>("Line")
                      .IsRequired()
                      .HasColumnType("character varying(255)")
                      .HasMaxLength(255);

            b.Property<string>("Platform")
                      .IsRequired()
                      .HasColumnType("character varying(255)")
                      .HasMaxLength(255);

            b.HasKey("Id");

            b.ToTable("Commands");
          });
#pragma warning restore 612, 618
    }
  }
}
